baseurl         = "/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "Joseph Ambayec Devlog"
  subtitle    = "Where all my projects go!"

  cover       = "img/preview16.png"
  description = "Joseph Ambayec's coding portfolio"
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "JosephAmbayec"
  fbName = "rickroll548"
  githubName = "Johari19"

  logo = ""
  orgName = "Contact: admin@josephambayec.dev"
  orgWebsite = "https://josephambayec.dev/about"
  orgDescription = ""

  author = "Joseph Ambayec"
  authorAvatar = "img/newjh.png"
  authorLocation = "Somewhere, ??"
  authorWebsite = "https://www.youtube.com/channel/UCtG0PJMoiVkWBxHZQbuMT6A"
  authorDescription = "Admin, Developper, Programmer"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Main"
  url = "/"
  weight = 200


[[menu.main]]
  name = "Projects"
  url = "/tags/Projects/"
  weight = 100

[[menu.main]]
  name = "Videos"
  url = "/tags/Videos/"
  weight = 99

[[menu.main]]
  name = "Youtube"
  url = "https://www.youtube.com/channel/UCtG0PJMoiVkWBxHZQbuMT6A"
  weight = 95
