backend:
  name: git-gateway
  branch: master

  media_folder: "static/uploads"
  public_folder: "uploads"

  collections:
  - title: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/post" # The path to the folder where the documents are stored

    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
