backend:
  name: git-gateway
  branch: master

media_folder: "/static/img"
public_folder: "/img"
collections:
  - label: "Post"
    name: "post"
    folder: "content/post"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
  

  - label: "Page"
    noauthor: true 
    draft: false 	
    share:  false 
    type: "page"
    name: "page"
    folder: "content/page"
    create: true
    fields:
    - {label: "Title of page", name: "title", widget: "string"} 
    - {label: "Weight in menu",widget: "number", default: 2, valueType: "int", min: 1, max: 101, 	step: 2}
    - {label: "Body", name: "body", widget: "markdown"}
    
